-- Verify Products table has VERSION column
SELECT COLUMN_NAME, TYPE_NAME, COLUMN_DEFAULT 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUCTS' AND COLUMN_NAME = 'VERSION';

-- Verify Orders table has correct TOTAL_AMOUNT precision
SELECT COLUMN_NAME, TYPE_NAME, NUMERIC_PRECISION, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ORDERS' AND COLUMN_NAME = 'TOTAL_AMOUNT';

-- Verify Carts table has UNIQUE constraint on (user_id, status)
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE 
FROM INFORMATION_SCHEMA.CONSTRAINTS 
WHERE TABLE_NAME = 'CARTS' AND CONSTRAINT_TYPE = 'UNIQUE';

-- Show all columns in products table
SELECT COLUMN_NAME, TYPE_NAME, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUCTS'
ORDER BY ORDINAL_POSITION;
